### ISSUE TITLE
Can't register to Dev version

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#1]
Tried to register a new user: control, all fields are filled. I do not get any error message, but the "register" button does not work.Sending 
![screen_shot - cannot register new user](https://cloud.githubusercontent.com/assets/12487248/8533076/38bff544-243b-11e5-9cda-59590fe41b7f.png)
![image](https://cloud.githubusercontent.com/assets/12487248/8533085/4ddd0f66-243b-11e5-9424-088435e74e32.png)

**Comment by arisprung** [comment]
I couldnt reproduce please try again and let me know
