### ISSUE TITLE
[Breathing] first screen

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#110]
This is the way it appears today (Different button, the text is missing):
![image](https://cloud.githubusercontent.com/assets/12487248/10814576/76de229e-7e2f-11e5-938d-4be32eef4e07.png)

and this is the design by Fay:
![image](https://cloud.githubusercontent.com/assets/12487248/10814587/8a1f6a0c-7e2f-11e5-911c-719df8ea2867.png)

**Comment by arisprung** [comment]
Fixed
