### ISSUE TITLE
[Questionnaire] location of comments/remarks space

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#111]
This is the current location:
![image](https://cloud.githubusercontent.com/assets/12487248/10814805/d7682690-7e30-11e5-9024-dfbd991dafb6.png)

This is the design:
![image](https://cloud.githubusercontent.com/assets/12487248/10814818/eaaa142a-7e30-11e5-81f9-5836aeb8d4bd.png)

**Comment by arisprung** [comment]
Fixed
