### ISSUE TITLE
Instructions alignment

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#112]
Now (left alignment):
![image](https://cloud.githubusercontent.com/assets/12487248/10814876/3c40092a-7e31-11e5-881b-dd934208842c.png)

Design (middle alignment):
![image](https://cloud.githubusercontent.com/assets/12487248/10814882/46311136-7e31-11e5-97c8-0e9699914704.png)

**Comment by arisprung** [comment]
Fixed
