### ISSUE TITLE
[Breathing] After recording

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#113]
Today (text in bubble is small, no under text)
![image](https://cloud.githubusercontent.com/assets/12487248/10814934/97578be4-7e31-11e5-8a10-9ce14dd90e6c.png)

Design:
![image](https://cloud.githubusercontent.com/assets/12487248/10814978/c8c0aa6c-7e31-11e5-8992-f4a775ea6e5b.png)

**Comment by arisprung** [comment]
Fixed
