### ISSUE TITLE
[breathing] - strings - development

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#116]
extra /n in the two first screens:
![breathing1](https://cloud.githubusercontent.com/assets/12487248/10867713/24310e92-807a-11e5-8ee6-f4cc01257040.png)
![breathing2](https://cloud.githubusercontent.com/assets/12487248/10867714/2432246c-807a-11e5-972c-1e1b8af0fb4a.png)

**Comment by MichaelG12345** [comment]
How come the UI is not respecting the linebreaks for this string?
In any event, if we want the "Aaaaaaaah..." and the "(as in Ark)" to be different sizes as in the UI design, then we need to split these into two separate string, no?

**Comment by arisprung** [comment]
Fixed
