### ISSUE TITLE
[Snippets - development] small stuff

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#117]
1- Breathing - space missing
2 - Mobility - a. space missing
b. extra n

![breathing snnipet](https://cloud.githubusercontent.com/assets/12487248/10867721/da9928f4-807a-11e5-80d8-6a110ff87434.png)
![mobility snnipet](https://cloud.githubusercontent.com/assets/12487248/10867722/da9a2e16-807a-11e5-8219-ab0900914f48.png)

**Comment by arisprung** [comment]
Fixe
