### ISSUE TITLE
Writing tasks images look strange

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#14]

**Comment by arisprung** [comment]
I need more info on this....

What do you mean by strange?Screeshot? the actual images like Home/Smiley?

**Comment by hagitta** [comment]
They are not adjusted to phone screen, the house looks blurry. The smiley is not circular, but rather oval. 
Also - the last test should be changed. I will write to Fay to ask her for an image.

**Comment by hagitta** [comment]
For the new version (1.3) - Images look much better. On my screen the house is a bit too large (screen shot attached) so it's difficult to trace the image accurately. 
![image](https://cloud.githubusercontent.com/assets/12487248/8639310/db55a63a-28de-11e5-83fe-cb04d64999a9.png)
