### ISSUE TITLE
[mobility task data]

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#150]
https://alsdevprize4life.hana.ondemand.com/als/api/tasks/stepTests
I only get full patient data, without accelerometer data at all.
a - should I be looking at a different link? which one?
b - if not - can you fix?

**Comment by MeiravDaniel** [comment]
Hi Hagit,

This change (Do not add axes to getAll  )was requested by Guy see attached
I implemented it.
If you want to see the axes you need to look at specific test like this:
https://alsdevprize4life.hana.ondemand.com/als/api/tasks/stepTests?id=1651

**Comment by MeiravDaniel** [comment]
not an issue
