### ISSUE TITLE
[Breathing task data]

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#151]
Hey,
Looking at the breathing task data saved from today I found some strange sorts of data. For example - see three different recordings for the same user - they strangely all have the same length:
190:  {
"id": 86500
"patientId": 86341
"created": "Jan 19, 2016 10:20:54 AM"
"recordings": [3]
0:  {
"id": 86501
"testId": 0
"length": 1405755842
}
-
1:  {
"id": 86502
"testId": 1
"length": 1405755842
}
-
2:  {
"id": 86503
"testId": 2
"length": 1405755842
}

Another strange finding is negative length:
189:  {
"id": 84752
"patientId": 2
"created": "Jan 17, 2016 8:28:23 AM"
"recordings": [1]
0:  {
"id": 84753
"testId": 0
"length": -340959117
}

**Comment by arisprung** [comment]
Fixed
