### ISSUE TITLE
[UI/UX] "Are you diagnosed with ALS?" screen

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#162]
In the "Are you diagnosed with ALS?" screen in the registration wizard, you'll notice that the help text below the radio buttons is smaller and lighter than the help texts in the other registration screens.
![image](https://cloud.githubusercontent.com/assets/12487248/13214614/6f0cdf4e-d959-11e5-91b0-6b50abf063f4.png)

**Comment by arisprung** [comment]
Fixe in new repo

**Comment by MichaelG12345** [comment]
The assistive string "If you answer no, your data...."  in the "Are you diagnosed..." screen seems to be hardcoded.
The correct string is in the strings.xml file:
<string name="non_als_info">If you aren\'t diagnosed with ALS, we\'ll use your data in the control group</string>

**Comment by MichaelG12345** [comment]
Ignore my last comment. In the new APK you sent, I now see the correct string from the strings file.
