### ISSUE TITLE
Logout --> registration of new user does not work

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#2]
Tried to logout from an already registered user and to create a new one. Creation works, but the app still "calls" me with the name of the previous user (For example: I logged out of one user after filling questionnaire, registered a new one, and got: 
![image](https://cloud.githubusercontent.com/assets/12487248/8533441/c625b336-243d-11e5-886d-10214418f9ae.png)
.

**Comment by arisprung** [comment]
Nice catch! Fixed in version 1.1-dev. PLease close issue after veryfing
