### ISSUE TITLE
Handwriting - Cleared image stays in memory

### ISSUE THREAD

**Issue by Limorerez** [Prize4Life/Android#45]
1. Open HandWriting test
2. draw some lines.
3. Clear all drawings.
4. go to finish step and press finish button.
5. The drawings which I cleared are saved in the

**Comment by hagitta** [comment]
Limor - I tried to reproduce and couldn't. Please try again and let me know if that's still as you described. Thanks!

**Comment by arisprung** [comment]
fixed
