### ISSUE TITLE
Registration Screen

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#66]
(bugs from Michael)

   -- None of the hard-coded strings I gave a couple of week ago for this UI have been updated. I have attached the file with the relevant string corrections.
   -- The app allows one to enter a diagnosis date that is earlier than the birth year.
  --  When tapping in the free text fields, it doesn’t show the cursor.
   -- I entered an invalid birth year and got the message “The year is not valid!”. The message should be “Year of birth is not valid.” and without an exclamation mark.

**Comment by arisprung** [comment]
fixed
