### ISSUE TITLE
Handwriting task:

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#70]
(From Michael)

    It’s possible to complete the task (press Next, Next etc. and then “Finish”) without actually doing any of the handwriting task => shows the “Sending files… Thank you for…” message and marks the task as done “Today” in the Home screen. If none of the handwriting task are completed, then user should get a message “No handwriting samples to submit”.
    When submitting a handwriting task, the user gets a toast message “Thanks for…” but it’s displayed too fast and then disappears. After a user submits a task the app should do the following:

    Display a toast message momentarily and which disappears on its own: Sending data…
    Then when it is sent successfully, there should be a popup which the user dismisses. The popup should have the following text:
      Title: Submit

  Body: Your task has been submitted
  Button: Close

**Comment by arisprung** [comment]
Fixed
