### ISSUE TITLE
Breathing

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#84]
When I tried to submit without performing the task got an error
"Unfortunately, ALS Mobile Analyzer has stopped."

**Comment by arisprung** [comment]
Does this reproduce? I cant find this crash in Crashlytics.

**Comment by hagitta** [comment]
yes. tried that again a moment ago. got this again:
![image](https://cloud.githubusercontent.com/assets/12487248/10621735/3224c676-778b-11e5-817c-ab3a05d17204.png)

**Comment by arisprung** [comment]
Not reproducing

**Comment by MichaelG12345** [comment]
I am getting this on v1.25 when I tap on Finish without making any breathing recordings.
