### ISSUE TITLE
Existing user email

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#95]
When I try to register a user who is already in the system, I have to go through the whole registration process, and only in the end I get this error (user existence should be checked when email is entered):
![image](https://cloud.githubusercontent.com/assets/12487248/10643442/894e1d94-782b-11e5-883f-51b291319c96.png)

**Comment by arisprung** [comment]
Guy - We need another api call for this to see if the email exist in db

**Comment by Limorerez** [comment]
APi exists.

**Comment by arisprung** [comment]
reopened - I still need to implemnt on client
