### ISSUE TITLE
all users become males

### ISSUE THREAD

**Issue by hagitta** [Prize4Life/Android#96]
I try to register female users, but I see that in the db they are registered as male.

**Comment by arisprung** [comment]
Guy

I am sending 0 for female and 1 for male.

Can you check on your side?

{"birthday":315596811284,"email":"aritestfemale@gmail.com
","diagnoseDate":315532800000,"gender":1,"repeatPassword":"1234","firstName":"www","password":"1234","userType":"PATIENT"}

Thanks
Ari

**Comment by arisprung** [comment]
Fixed
